### ISSUE TITLE
Objects inside an array coming from a source connector have their types set to string in the generated Schema

### ISSUE THREAD

**Issue by farhadnowzari** [neo4j-contrib/neo4j-streams#639] opened 2024-07-19 16:01 UTC
## Expected Behavior (Mandatory)

We have a cypher, where at the end will generate an output like this, if it is ran against neo4j:
```json
{
    "name": "Movie#1",
    "resources": [
        {
            "name": "Camera",
            "isUsed": false
        },
        {
            "name": "Light",
            "isUsed": true
        }
    ]
}
```

if the resources objects have a value of type boolean or integer, the connector fails after reading one node into the topic and it complains with such error `Invalid Java object for schema with type STRING: class java.lang.Long`

We are using the neo4j-connector version 5.0.2 against neo4j 5.19 with `confluentinc/cp-kafka-connect-base:6.2.1`

## Actual Behavior (Mandatory)

The objects inside an array should have their types kept and not be converted to String, because neo4j cypher is going to return boolean or long or any other type which cannot be casted to STRING.

## How to Reproduce the Problem

The actual query is much bigger, but the following one kinda give the idea how our case look like.
```
MATCH (m:Movie)
WITH m

CALL {
    WITH m
    OPTIONAL MATCH (m)-[:HAS]->(r:Resource)
    WITH m,r
    RETURN collect({ id: r.id, name: r.name, isUsed: COALESCE(r.isUsed, false) }) as resources
}

WITH *
RETURN
    m.id as id,
    resources
```

### Steps (Mandatory)

  1. Install the above cypher with a source connector with such config:
  ```json
    {
    "connector.class": "streams.kafka.connect.source.Neo4jSourceConnector",
    "errors.log.include.messages": "true",
    "topic.creation.default.partitions": "-1",
    "transforms.extractKeyFromStruct.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
    "neo4j.authentication.basic.password": "<pass>",
    "transforms": "ValueToKey,extractKeyFromStruct",
    "transforms.extractKeyFromStruct.field": "id",
    "topic.creation.applicationlogs.cleanup.policy": "delete",
    "neo4j.database": "<db-name>",
    "neo4j.streaming.property": "modifiedUtc",
    "topic.creation.applicationlogs.retention.ms": "10000",
    "neo4j.enforce.schema": "true",
    "topic.creation.default.replication.factor": "3",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "errors.log.enable": "true",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "transforms.ValueToKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
    "errors.retry.timeout": "-1",
    "neo4j.server.uri": "<neo4j-address>",
    "neo4j.source.query": "",
    "errors.retry.delay.max.ms": "30000",
    "transforms.ValueToKey.fields": "id",
    "key.converter.schemas.enable": "true",
    "topic.creation.inventory.delete.retention.ms": "10000",
    "name": "<name>",
    "value.converter.schemas.enable": "false",
    "neo4j.authentication.basic.username": "<neo-user>",
    "topic": "topic",
    "errors.tolerance": "all",
    "neo4j.streaming.poll.interval.msecs": "200",
    "neo4j.streaming.from": "LAST_COMMITTED"
    }
  ```
  2. After one read it fails and cannot reading the rest, with the error mentioned at the beginning. The stacktrace comes at the end

## Specifications (Mandatory)

* cp-kafka-connect: container base image -> confluentinc/cp-kafka-connect-base:6.2.1
* kafka-neo4j-connect: neo4j/kafka-connect-neo4j:5.0.2
* neo4j db: 5.19

The schema registry service from kafka is not deployed.

### Versions

  - OS: We are running in kubernetes 1.29
  - Neo4j: 5.19
  - Neo4j-Streams: 5.02

### Stacktrace

```
org.apache.kafka.connect.errors.ConnectException: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema with type STRING: class java.lang.Long\n\tat streams.kafka.connect.source.Neo4jSourceService.checkError(Neo4jSourceService.kt:131)\n\tat streams.kafka.connect.source.Neo4jSourceService.poll(Neo4jSourceService.kt:139)\n\tat streams.kafka.connect.source.Neo4jSourceTask.poll(Neo4jSourceTask.kt:31)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:296)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:253)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\nCaused by: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema with type STRING: class java.lang.Long\n\tat org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:242)\n\tat org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)\n\tat org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:261)\n\tat org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:213)\n\tat org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:255)\n\tat org.apache.kafka.connect.data.Struct.put(Struct.java:216)\n\tat streams.kafka.connect.utils.ConnectExtensionFunctionsKt.asStruct(ConnectExtensionFunctions.kt:42)\n\tat streams.kafka.connect.source.SourceRecordBuilder.build(SourceRecordBuilder.kt:59)\n\tat streams.kafka.connect.source.Neo4jSourceService.toSourceRecord(Neo4jSourceService.kt:107)\n\tat streams.kafka.connect.source.Neo4jSourceService.access$toSourceRecord(Neo4jSourceService.kt:28)\n\tat streams.kafka.connect.source.Neo4jSourceService$job$1.invokeSuspend$lambda-1(Neo4jSourceService.kt:84)\n\tat org.neo4j.driver.internal.InternalSession.lambda$transaction$4(InternalSession.java:137)\n\tat org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:106)\n\tat org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:134)\n\tat org.neo4j.driver.internal.InternalSession.readTransaction(InternalSession.java:103)\n\tat streams.kafka.connect.source.Neo4jSourceService$job$1.invokeSuspend(Neo4jSourceService.kt:79)\n\tat kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)\n\tat kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)\n\tat kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)\n\tat kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)\n\tat kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)\n
```

**Comment by farhadnowzari** [comment] 2024-07-19 17:19
I updated to `5.0.5` and now the error changed to: For Schema.Type.STRUCT we support only Map and Point

**Comment by Emrehzl94** [comment] 2024-07-29 06:50
Hi @farhadnowzari, I tested with version 5.0.5 and got the expected result. Could you please provide the whole query?
And I recommend you to use `confluentinc/cp-server-connect:7.3.0` container image for connect if you don't have a dependency on the current one.

**Comment by farhadnowzari** [comment] 2024-08-08 14:09
> Hi @farhadnowzari, I tested with version 5.0.5 and got the expected result. Could you please provide the whole query? And I recommend you to use `confluentinc/cp-server-connect:7.3.0` container image for connect if you don't have a dependency on the current one.

So I did the update to `cp-server-connect:7.3.0`, but I still get the error. The data which I'm trying to send, I have attached with the message.

[records.json](https://github.com/user-attachments/files/16549234/records.json)

**Comment by Emrehzl94** [comment] 2024-08-12 14:32
Looks like there is a bug, when query returns object list and if the first element of the list has a null value, like the example below;

```
{
    "name": "Movie#1",
    "resources": [
        {
            "name": null,
            "isUsed": false
        },
        {
            "name": "Light",
            "isUsed": true
        }
    ]
}
```

if so, it's not able to correctly determine schema for the data. 

For now, as workaround solution you can either remove `"neo4j.enforce.schema": "true"` property from configuration but in this case, value schema will be **String** type or provide a default value for each value which is returning from query by using **COALESCE**.

Another solution would be to use latest connector version which is **5.1.0-rc02** but you will need to do small migration on the configuration. 

This is the public repo for the latest version of connector; https://github.com/neo4j/neo4j-kafka-connector

**Comment by Emrehzl94** [comment] 2024-08-16 13:18
I'm closing this issue as it is no longer reproducible in the latest version. Please feel free to reopen it if the problem occurs again.

**Closed by Emrehzl94** 2024-08-16 13:18 UTC

**Comment by farhadnowzari** [comment] 2024-09-10 09:28
> I'm closing this issue as it is no longer reproducible in the latest version. Please feel free to reopen it if the problem occurs again.

So the error apparently is gone with 5.1.1, but I am getting this strange data in the topic:

![image](https://github.com/user-attachments/assets/60a4a047-408e-4179-97d0-9d2ab761657e)


On the other end as the sink connector, I have elastic sink connector and the sink connector fails now.

Is this now how the neo4j connector serializes the data? how can I use it with elastic now?

**Comment by farhadnowzari** [comment] 2024-09-10 10:40
> > I'm closing this issue as it is no longer reproducible in the latest version. Please feel free to reopen it if the problem occurs again.
> 
> So the error apparently is gone with 5.1.1, but I am getting this strange data in the topic:
> 
> ![image](https://private-user-images.githubusercontent.com/57224511/365981733-60a4a047-408e-4179-97d0-9d2ab761657e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjUwNzEsIm5iZiI6MTcyNTk2NDc3MSwicGF0aCI6Ii81NzIyNDUxMS8zNjU5ODE3MzMtNjBhNGEwNDctNDA4ZS00MTc5LTk3ZDAtOWQyYWI3NjE2NTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDEwMzkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmODc4YjRlNTNhYjgyYzc0ZGJiZWE5ZmM1ZWQ3ZWZiMWNkZGJmMTU4MGVkZTk0OWRjZWQzMjBkNjgxMzgyNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OMhGo_gWM7jGoPbE4QYYEzLQ6OYo_H0CVend6BNoYj4)
> 
> On the other end as the sink connector, I have elastic sink connector and the sink connector fails now.
> 
> Is this now how the neo4j connector serializes the data? how can I use it with elastic now?

As I see, this format also is expected in elastic. So the sink connector if the index doesn't exist, will create an elastic index with the exact same json, but then it is not valid. How can we normailize the data
