### ISSUE TITLE
Add a way to externalize the Cypher to execute per batch

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-streams#286] opened 2020-02-25 18:53 UTC
## Feature description
In the [Cypher template](https://neo4j.com/docs/labs/neo4j-streams/current/#_cypher_template_2) of the sink configuration, you can currently provide Cypher that will be executed per row of the batch (after the UNWINDing of the batch as `event`). 

It would be useful to provide an alternate approach which can reference an external Cypher file and use that for execution (such that the Cypher from the file is amended, the UNWIND being appended to the beginning, and then cached so the file read doesn't happen per batch).

This would pair nicely with #155 , specifically a procedure to refresh the Cypher by rereading the file, allowing runtime changes based on changes to the Cypher in the file.

## How this feature can improve the project?
This adds runtime flexibility, and decouples the Cypher from the template file.

**Comment by moxious** [comment] 2020-10-01 16:08
Closing this specifically because I think it's a duplicate of the referenced issue above -- which we've updated with status & discussion.

**Closed by moxious** 2020-10-01 16:08 UTC
