### ISSUE TITLE
Make sure to confirm/commit that messages have been successful consumed

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-streams#97] opened 2018-11-30 08:35 UTC
So that when the cypher statement is not executed successfully, the are still available in the topic.

**Comment by surajrrao** [comment] 2019-05-04 08:31
@jexp / @conker84 - I am currently evaluating Neo4j sink connector and I don't see the offset is being committed to the offset topic. Any idea?

**Comment by jexp** [comment] 2019-05-04 15:24
My Kafka-fu is a bit weak, could you explain this more or point to docs/examples? Thank you!

**Comment by surajrrao** [comment] 2019-05-04 18:45
Hi @jexp ,

I am following this blog post - https://www.confluent.io/blog/kafka-connect-neo4j-sink-plugin

I have downloaded the kafka-connect-neo4j:1.0.0 plugin & added to my connect plugin folder.

Here is my connect docker config

connect:
    image: confluentinc/cp-kafka-connect
    hostname: connect
    container_name: connect    
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - 8083:8083
    volumes:
    - ./Documents/confluent-kafka-community/connect-plugins:/tmp/connect-plugins      
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      **CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets**
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_KEY_SUBJECT_NAME_STRATEGY: "io.confluent.kafka.serializers.subject.TopicRecordNameStrategy"
      CONNECT_VALUE_CONVERTER_VALUE_SUBJECT_NAME_STRATEGY: "io.confluent.kafka.serializers.subject.TopicRecordNameStrategy"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/tmp/connect-plugins"

Here is my Neo4j sink connector job

curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" localhost:8083/connectors/ -d '{
  "name": "user-data-neo4j-sink-connector",
  "config": {
  	"tasks.max": "1",
	"topics": "user_data",
	"connector.class": "streams.kafka.connect.sink.Neo4jSinkConnector",
	"errors.retry.timeout": "-1",
	"errors.retry.delay.max.ms": "1000",
	"errors.tolerance": "none",
	"errors.log.enable": true,
	"errors.log.include.messages": true,
	"neo4j.server.uri": "bolt://neo4j:7687",
	"neo4j.authentication.basic.username": "neo4j",
	"neo4j.authentication.basic.password": "connect",
	"neo4j.encryption.enabled": false,
	"neo4j.topic.cypher.user_data": "MERGE (u:User { uid: event.uid }) SET u.first_name= u.first_name, u.last_name= u.last_name"
  }
}'


Everything works fine, I see the job is running and writing data on to my neo4j instance from topic.
 
Except, I don't see that the kafka topic offset for this connector is getting committed in the offset topic configured above - **CONNECT_OFFSET_STORAGE_TOPIC**. It is important to track the topic offset for each connector, so incase if we restart the connector - it know's at what point to start reading the messages from the topic.  Currently, I see if i restart the connector it's re-processing the messages from the beginning always.

**Comment by conker84** [comment] 2019-05-15 11:01
Hi @surajrrao according to this [answer on SO](https://stackoverflow.com/questions/41492347/kafka-connect-offset-storage-topic-not-receiving-messages-i-e-how-to-access-ka#answer-42641087) the `offset.storage.topic` is used only with Source plugins; the Sink plugins commit on `__consumer_offsets`.
I did a try with Neo4j Sink Plugin and I was not able to reproduce the "re-processing" can you please share (only the delta was processed) the steps that you followed?

**Comment by conker84** [comment] 2019-05-17 08:54
@surajrrao ping

**Comment by moxious** [comment] 2020-10-01 16:20
Closing this in light of the DLQ improvements, which happened some time ago.

**Closed by moxious** 2020-10-01 16:20 UTC
