### ISSUE TITLE
Allow pointing to a cypher file instead of needing to write the cypher in the neo4j.conf for the consumption of a topic

### ISSUE THREAD

**Issue by rhaces** [neo4j-contrib/neo4j-streams#289] opened 2020-03-10 23:30 UTC
Currently, you need to enter the full cypher in the neo4j.conf file for each topic you want to consume (as explained here https://neo4j.com/docs/labs/neo4j-streams/current/#_sink), however this is very inconvenient when either you have multiple topics to consume or you have a complex cypher.

The request is to allow pointing each topic to a cypher (`.cyp`) file that will contain the cypher to use to consume the topic.

**Comment by mroiter-larus** [comment] 2020-03-11 08:22
Hi @rhaces, i think this is a duplicate of #286

**Comment by rhaces** [comment] 2020-03-11 13:39
@mroiter-larus It is definitely related, but not duplicated. From what I read, #286 talks about the Kafka Connect Plugin, where this refers to the Neo4j Streams Plugin (see https://neo4j.com/docs/labs/neo4j-streams/current/#_neo4j_streams_plugin_2)

**Comment by moxious** [comment] 2020-03-12 18:22
I recently talked to @rhaces on the phone, and suggested some more architectural fixes for this rather than better enabling people to write really large cypher queries.    Please leave this pending for the moment, I would like to link this architecture stuff back to this issue, as I think it might be a better approach to solve the underlying issues.

**Comment by moxious** [comment] 2020-10-01 16:07
This is an important ticket, but we need more internal team discussion on how to move forward with it.  The issue is that what users really need is a work-around for the neo4j static configuration system to allow dynamic cypher.

The options are not wonderful.  One option is to store the queries in the database and then match the query node and use apoc.cypher.doIt.   In this particular case, the customer may have used apoc.cypher.runFile, but this is a very bad approach since it does repeated disk IO for the file over and over again -- under large amounts of load.  It's quite negative for performance.

In my opinion the root issue here is lack of dynamic configuration in Neo4j, which obviously affects Neo4j-streams as well.   We need some basic brainstorming on the best approach to deal with that, rather than the addition of a cypher file on disk configuration item.

**Comment by FrankR85** [comment] 2020-11-23 13:26
As a dirty workaround we wrote a script which is executed during the build of our `Dockerimage`:
```bash
#!/bin/bash
#For each file filename.cypher in the cypher-Folder 
# an entry is added to conf/neo4j.conf:
#    streams.sink.topic.cypher.<<filename>>=<<content of file>>
configfile=$NEO4J_HOME/conf/neo4j.conf
for filename in $(find cypher -name '*.cypher'); do 
  echo >> $configfile 
  cat <(echo 'streams.sink.topic.cypher.'$(basename $filename .cypher)'=') $filename  \
              | tr '\r\n' ' ' >> $configfile 
done
```
Not nice, but better than C&P the cypherquery, removing linefeeds etc... manualy.

**Comment by ali-ince** [comment] 2023-09-14 09:52
closing this as streams plugin is now deprecated and no new features are planned.

**Closed by ali-ince** 2023-09-14 09:52 UTC
