### ISSUE TITLE
Neo4j Session.save takes more than 30 min after enabling CDC

### ISSUE THREAD

**Issue by Balatriveni** [neo4j-contrib/neo4j-streams#129] opened 2019-01-08 21:58 UTC
## Guidelines

We enabled Neo4j CDC through kafka using the neo4j streams plugin. After that when we are trying to save the node using neo4j spring boot application with Session.Save it takes more than 30 sec.. 

  session.clear();
                    session.save(style);
                    session.save(customerChoice);
                    session.save(domainsku);
or transacation.commit takes lot of time. 

if we disable neo4j streams plugin then it works fine.
### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Streams:

**Comment by jexp** [comment] 2019-01-09 07:09
can you provide more details?

what does your kafka config look like
and your cdc settingns

what kinds of subgraphs do you store? size and structure
perhaps you have an example project that makes this reproducible.

**Comment by Balatriveni** [comment] 2019-01-09 23:31
neo4j.conf looks like below:
# Kafka Connector Config #
kafka.bootstrap.servers=xx
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=SCRAM-SHA-512
kafka.sasl.jaas.config= xx
#** Neo4j Config for Kafka **
streams.procedures.enabled=true

#CDC for Nodes
streams.source.topic.nodes.neo4j-styles=Style{*}
#CDC for Relationships
#streams.source.topic.relationships.<TOPIC_NAME>=<PATTERN>ram.ScramLoginModule req
[EntityProcessor.txt](https://github.com/neo4j-contrib/neo4j-streams/files/2742996/EntityProcessor.txt)

uired username="sincere-antelope.RQBB$
#streams.source.topic.nodes.neo4j-choices=CustomerChoice{*}
#streams.source.topic.nodes.neo4j-skus=SKU{*}

the graph which we are storing as Style, CC, SKU and all these nodes will have relationships. 
I uploaded the entity processor code.. hopefully that would help you

**Comment by jexp** [comment] 2019-01-09 23:37
How many/which properties does Style have?

What is the usal size of a batch that you save with your session?

**Comment by jexp** [comment] 2019-01-09 23:40
What is your infrastructure setup, i.e. are the spring app and kafka runninng in the same AZ ?

And is each save slowed down to 30s?

**Comment by Balatriveni** [comment] 2019-01-09 23:41
> Size means entities and their related entities/properties.

**Comment by jexp** [comment] 2019-01-09 23:42
what happened?

**Comment by Balatriveni** [comment] 2019-01-09 23:44
> What is your infrastructure setup, i.e. are the spring app and kafka runninng in the same AZ ?
> 
> And is each save slowed down to 30s?

We have hosted neo4j in aws ec2 instance.. and I am running the spring boot application in local .. 
without applying kafka plugin it saves very fast.. but after enabling it slows down

**Comment by Balatriveni** [comment] 2019-01-09 23:44
Also sorry by mistak

> what happened?

by mistake the issue was closed.
let me reopen

**Comment by jexp** [comment] 2019-01-09 23:49
and kafka runs in aws?
which kafka service do you use? so we can reproduce for testing?

**Comment by Balatriveni** [comment] 2019-01-09 23:57
we have an internal proton kafka team which is hosted in aws .. 
I am currently using transaction & session.save  not sure if we have a different patterns for saving...

**Comment by Balatriveni** [comment] 2019-01-09 23:57
Also I can setup an bluejeans request if you want to look at our local environment.

**Comment by conker84** [comment] 2019-01-10 08:37
Hi @Balatriveni do you have more datails about the size of your graph in terms of nodes/relationships?

**Comment by conker84** [comment] 2019-01-10 10:20
Hi @Balatriveni if it's possible to take a look to your env would be great

**Comment by albertodelazzari** [comment] 2019-01-10 14:03
> > What is your infrastructure setup, i.e. are the spring app and kafka runninng in the same AZ ?
> > And is each save slowed down to 30s?
> 
> We have hosted neo4j in aws ec2 instance.. and I am running the spring boot application in local ..
> without applying kafka plugin it saves very fast.. but after enabling it slows down
> 
> also our node is currently with 10 properties and each node has 2/3 relationship at max

Hi, @Balatriveni, just to be sure you're aware of how `session.save` works. According to Neo4j-OGM the official documentation:

> As mentioned previously, save(entity) is overloaded as save(entity, depth), where depth dictates the number of related entities to save starting from the given entity. The default depth, -1, will persist properties of the specified entity as well as every modified entity in the object graph reachable from it. This means that all affected objects in the entity model that are reachable from the root object being persisted will be modified in the graph. This is the recommended approach because it means you can persist all your changes in one request. Neo4j-OGM is able to detect which objects and relationships require changing, so you won’t flood Neo4j with a bunch of objects that don’t require modification. You can change the persistence depth to any value, but you should not make it less than the value used to load the corresponding data or you run the risk of not having changes you expect to be made actually being persisted in the graph. A depth of 0 will persist only the properties of the specified entity to the database.

> Specifying the save depth is handy when it comes to dealing with complex collections, that could potentially be very expensive to load.

This could mean that when you save your `style`, `customerChoice` or `domainsku` objects, all the relationships and nodes that are reachable from these 3 nodes (and are marked as modified entities) will be modified. This can lead to a large subgraph query. I can't say this is your case but it could be one of the root causes of the problem.

Thanks

**Comment by Balatriveni** [comment] 2019-01-10 16:39
@conker84 
we have 81 million nodes and 124 million relationships in our current aws instance.. 
If you want I can set up a blue jeans request tomorrow 1/11 around 7 am PST if that works.

**Comment by Balatriveni** [comment] 2019-01-10 16:40
> 1

**Comment by Balatriveni** [comment] 2019-01-10 16:41
@albertodelazzari  I will try saving by specifying the depth.. we only have node and its relationships.
All the relationships are in 1 level depth.

**Comment by conker84** [comment] 2019-01-13 17:52
@Balatriveni can you give us a feedback about the @albertodelazzari's suggestion?

**Comment by Balatriveni** [comment] 2019-01-14 19:52
@albertodelazzari  it saves properly if we depth as 0. 
If we keep depth 1 then it is taking lot of time
also when we do MATCH (n:CustomerChoice) where n.ShortName = '2034161797_test' detach delete n this also takes lot of time...

**Comment by Balatriveni** [comment] 2019-01-15 19:00
@albertodelazzari Yes you are right Customer choice will have SKU as a child and style as a parent.. 
please find the hierarchy
<img width="576" alt="hierarchy" src="https://user-images.githubusercontent.com/46504306/51202914-ae5cad80-18b4-11e9-9268-7dc0a82352f0.png">

**Comment by Balatriveni** [comment] 2019-01-21 22:47
@albertodelazzari any update on this?

**Comment by jexp** [comment] 2019-03-14 15:17
Investigate the scenarion/pattern when this happens.
In general in no case we want to add additional time to the tx-execution, that's why we're also writing asynchronously.

**Comment by jexp** [comment] 2019-03-14 15:18
perhaps we can use @moxious' load tester for trying to reproduce the scenario!

**Comment by conker84** [comment] 2020-11-10 09:05
@Balatriveni we found a potential problem with the DNS resolution in some specific environments and looking back to this issue I think that it may be related. Can you please give a try to the last version?

**Comment by conker84** [comment] 2020-11-18 08:41
I'm closing this since a lack of feedback, feel free to reopen in case you have any new information

**Closed by conker84** 2020-11-18 08:41 UTC
