### ISSUE TITLE
Cant able to consume data from kafka

### ISSUE THREAD

**Issue by vishnu2497** [neo4j-contrib/neo4j-streams#346] opened 2020-09-03 07:03 UTC
Hi All,

i am just trying to perform sample neo4j sink from kafka,But that connector is not starting and there is no clear resource available too

i installed connector using this following command from confluet-hub

> confluent-hub install neo4j/kafka-connect-neo4j:1.0.7

i am using **Confluent kafka latest verison in Docker**

This is the configuration i am having.

> {
>   "name": "sink-neo-test1",
>   "config": {
>     "topics": "neo4-order",
>     "connector.class": "streams.kafka.connect.sink.Neo4jSinkConnector",
>     "errors.retry.timeout": "-1",
>     "errors.retry.delay.max.ms": "1000",
>     "errors.tolerance": "all",
>     "errors.log.enable": true,
>     "errors.deadletterqueue.topic.name": "test-error-topic",
>     "errors.log.include.messages": true,
>     "neo4j.server.uri": "bolt://neo4j:7687",
>     "neo4j.authentication.basic.username": "neo4j",
>     "neo4j.authentication.basic.password": "test7",
>     "neo4j.encryption.enabled": false,
>     "neo4j.topic.cypher.neo4-order": "MERGE (n:Label {id: event.id}) ON CREATE SET n += event.properties"
>   }
> }

and this is my error log.

`(streams.kafka.connect.sink.Neo4jSinkConnectorConfig)
[2020-09-03 06:48:07,986] ERROR WorkerConnector{id=sink-neo-test1} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector)
java.lang.NoClassDefFoundError: Could not initialize class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader
	at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:148)
	at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(JvmBuiltIns.kt:56)
	at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(JvmBuiltIns.kt:31)
	at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:57)
	at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:35)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:32)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:46)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:43)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:172)
	at kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:186)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:90)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:43)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:222)
	at streams.kafka.connect.sink.Neo4jSinkConnectorConfig.validateAllTopics(Neo4jSinkConnectorConfig.kt:347)
	at streams.kafka.connect.sink.Neo4jSinkConnectorConfig.<init>(Neo4jSinkConnectorConfig.kt:111)
	at streams.kafka.connect.sink.Neo4jSinkConnector.start(Neo4jSinkConnector.kt:25)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:111)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:136)
	at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:196)
	at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:264)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:1190)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:126)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1206)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$14.call(DistributedHerder.java:1202)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2020-09-03 06:48:07,995] INFO Finished creating connector sink-neo-test1 
`

can anyone knows how to fix this.?

**Comment by mroiter-larus** [comment] 2020-09-03 10:04
Hi @vishnu2497,

which Neo4j version are you using?

**Comment by vishnu2497** [comment] 2020-09-03 12:01
4.0.4 @mroiter-larus

**Comment by mroiter-larus** [comment] 2020-10-05 08:15
@vishnu2497 We are working in order to replicate the issue. I hope to give you a feedback asap. I'm sorry for the delay in replying.

**Comment by mroiter-larus** [comment] 2020-10-06 22:38
@vishnu2497 When using Kafka Connect Sink plugin, if you enable the DLQ functionality you have also to provide the following property:

```
kafka.bootstrap.servers: "<Kafka broker url>"
```
Please see [here](https://neo4j.com/labs/kafka/4.0/kafka-connect/#kafka_connect_error_handling) for further details.

Hope this helps

**Comment by mroiter-larus** [comment] 2020-10-14 14:42
@vishnu2497 Any news?

**Comment by mroiter-larus** [comment] 2020-10-19 12:46
@vishnu2497 ping

**Comment by conker84** [comment] 2020-11-10 08:44
@vishnu2497 I'm closing this since there is no feedback, feel free to reopen in case you have more info to share

**Closed by conker84** 2020-11-10 08:44 UTC

**Comment by antonio-urbano** [comment] 2021-03-03 14:44
@conker84  @mroiter-larus  I ran into the same problem without being able to solve it. This is the error log:

{"name":"Neo4jSinkConnector","connector":{"state":"FAILED","worker_id":"connect:8083","trace":"java.lang.NoClassDefFoundError: Could not initialize class kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader\n\tat kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:148)\n\tat kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(JvmBuiltIns.kt:56)\n\tat kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(JvmBuiltIns.kt:31)\n\tat kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:57)\n\tat kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)\n\tat kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:35)\n\tat kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:32)\n\tat kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)\n\tat kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)\n\tat kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt)\n\tat kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:46)\n\tat kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:43)\n\tat kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)\n\tat kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)\n\tat kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt)\n\tat kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:172)\n\tat kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:186)\n\tat kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:90)\n\tat kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:43)\n\tat kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)\n\tat kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)\n\tat kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(KClassImpl.kt)\n\tat kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:222)\n\tat streams.kafka.connect.sink.Neo4jSinkConnectorConfig.validateAllTopics(Neo4jSinkConnectorConfig.kt:347)\n\tat streams.kafka.connect.sink.Neo4jSinkConnectorConfig.<init>(Neo4jSinkConnectorConfig.kt:111)\n\tat streams.kafka.connect.sink.Neo4jSinkConnector.start(Neo4jSinkConnector.kt:25)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:185)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:210)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:349)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:332)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:140)\n\tat org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:117)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n"},"tasks":[],"type":"sink"}

**Comment by conker84** [comment] 2021-03-03 14:52
@antonio-urbano can you please highlight Neo4j and kafka version?

**Comment by antonio-urbano** [comment] 2021-03-03 15:02
@conker84 
I'm using neo4j:4.0.3
Kafka connect v: 1.0.9

**Comment by conker84** [comment] 2021-03-03 15:04
Yes I also need the Kafka version

**Comment by conker84** [comment] 2021-03-03 15:04
Or the Confluent version if you're using the Confluent Platform

**Comment by antonio-urbano** [comment] 2021-03-03 15:12
@conker84 
I'm using the following image in docker 
confluentinc/cp-enterprise-kafka

**Comment by conker84** [comment] 2021-03-03 15:13
can you please try with `confluentinc/cp-enterprise-kafka:5.5.2`?

**Comment by conker84** [comment] 2021-03-03 15:14
please consider to update other Confluent deps in your compose file to the same version

**Comment by antonio-urbano** [comment] 2021-03-03 15:46
@conker84 It seems that I solved the problem using this version of kafka
I'm not completely sure because now I have problem with the replication factor (even if I set the configuration in my docker compose with 1 replication on the connector) with this error log. But the connector now is working, so I think I solved the required issue. Thanks for assistance

{"name":"Neo4jSinkConnector","connector":{"state":"RUNNING","worker_id":"connect:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"connect:8083","trace":"org.apache.kafka.connect.errors.ConnectException: Could not initialize dead letter queue with topic=test-error-topic\n\tat org.apache.kafka.connect.runtime.errors.DeadLetterQueueReporter.createAndSetup(DeadLetterQueueReporter.java:93)\n\tat org.apache.kafka.connect.runtime.Worker.sinkTaskReporters(Worker.java:797)\n\tat org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:634)\n\tat org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:555)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1259)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1700(DistributedHerder.java:128)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1274)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1270)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)\n\tat org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)\n\tat org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)\n\tat org.apache.kafka.connect.runtime.errors.DeadLetterQueueReporter.createAndSetup(DeadLetterQueueReporter.java:87)\n\t... 11 more\nCaused by: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.\n"}],"type":"sink"}

**Comment by antonio-urbano** [comment] 2021-03-03 16:14
@conker84 With this version the connector seems to work. Thanks for the assistance
